import { Images } from '@/shared/assets';
import { Products } from './types';

export const cartProducts: Products = [
  {
    id: 1,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_1,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 2,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_1,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 3,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_1,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 4,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_1,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 5,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_1,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
];
export const products: Products = [
  {
    id: 1,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 2,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 3,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 4,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 5,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 6,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 7,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 8,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 9,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 10,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 11,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
  {
    id: 12,
    name: 'Essence Mascara Lash Princess',
    price: 110,
    image: Images.PRODUCT_CATALOG,
    discount: 14.5,
    count: 1,
    priceWithoutDiscount: 110,
    priceTotal: 110,
  },
];
